### ISSUE TITLE
WebSockets & Unhandled rejection TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by awwong1** [maciejtreder/serverless-apigw-binary#50]
When using the [websocket events](https://serverless.com/framework/docs/providers/aws/events/websocket/) with the apigwBinary plugin, a unhandled rejection TypeError is thrown.

* serverless `v1.38.0`
* serverless-apigw-binary `0.4.4`

I do not get this error when the websocket event handlers are not defined in the yml file.

```yml
functions:
  # ...
  connectionHandler:
    handler: dist/handler.wsConnectionHandler
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - "*/*"
```

```typescript
export const wsConnectionHandler: Handler = async (event: any, context: Context) => {
  // const domain = event.requestContext.domainName;
  // const stage = event.requestContext.stage;
  // const connectionId = event.requestContext.connectionId;
  // // construct the needed url
  // const callbackUrlForAWS = format(format("https://%s/%s", domain, stage));
  // await sendMessageToClient(callbackUrlForAWS, connectionId, event);

  return {
    statusCode: 200
  };
};
```

```
Unhandled rejection TypeError: Cannot read property '1' of null
    at provider.request.then.resp (/home/alexander/sandbox/src/git.udia.ca/udia-software/udia-ssr/node_modules/serverless-apigw-binary/src/index.js:19:67)
    at tryCatcher (/home/alexander/sandbox/src/git.udia.ca/udia-software/udia-ssr/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/alexander/sandbox/src/git.udia.ca/udia-software/udia-ssr/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/alexander/sandbox/src/git.udia.ca/udia-software/udia-ssr/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/alexander/sandbox/src/git.udia.ca/udia-software/udia-ssr/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/alexander/sandbox/src/git.udia.ca/udia-software/udia-ssr/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/alexander/sandbox/src/git.udia.ca/udia-software/udia-ssr/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/alexander/sandbox/src/git.udia.ca/udia-software/udia-ssr/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/alexander/sandbox/src/git.udia.ca/udia-software/udia-ssr/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues (/home/alexander/sandbox/src/git.udia.ca/udia-software/udia-ssr/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

**Comment by davidsoendoro** [comment]
Hi, is there any updates regarding this issue? I found that it is because of the assumption of api urls always start with https while in websocket it is possible that the url starts with wss. I did the dirty fix by modifying the index.js file like followings

```
  ...

  getApiId(stage) {
    return new Promise(resolve => {
      this.provider.request('CloudFormation', 'describeStacks', { StackName: this.provider.naming.getStackName(stage) }).then(resp => {
        const output = resp.Stacks[0].Outputs;
        let apiUrl;
        output.filter(entry => entry.OutputKey.match('ServiceEndpoint')).forEach(entry => apiUrl = entry.OutputValue);
        const apiMatches = apiUrl.match('https:\/\/(.*)\\.execute-api');
        if (apiMatches && apiMatches.length > 1) {
          const apiId = apiMatches[1];
          resolve(apiId);  
        } else {
          resolve(null);
        }
      });
    });
  }

  ...

  afterDeploy() {
    const mimeTypes = this.serverless.service.custom.apigwBinary.types;
    const swaggerInput = JSON.stringify({
      "swagger": "2.0",
      "info": {
        "title": this.getApiGatewayName()
      },
      "x-amazon-apigateway-binary-media-types": mimeTypes
    });
    const stage = this.options.stage || this.serverless.service.provider.stage;

    return this.getApiId(stage).then(apiId => {
      if (apiId) {
        return this.putSwagger(apiId, swaggerInput).then(() => {
          return this.createDeployment(apiId, stage);
        });  
      }
    });
  }

  ...
```

I don't know though if this "fix" will not lead to any more problems but it manages to get my functions deployed to AWS. An official fix would be a great help :).

**Comment by jkapongo** [comment]
Not quite sure if this still relevant, but I avoid this error by _not_ using this plugin. I instead set `binaryMediaTypes` directly from my `serverless.yml` file. Here's a snippet:
```
  apiGateway:
    binaryMediaTypes:
      - '*/*'
 ```
